import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { PostsState } from './reducers/posts.reducers';
import { Post } from './interfaces/post';
import { LoadPosts } from './post.actions';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  posts: Post[] = [
    {id: '1', title: '1 Sed ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '2', title: '2 Ut enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '3', title: '3 Et harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '4', title: '4 Sed ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '5', title: '5 Uno enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '6', title: '6 Et harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '7', title: '7 Meni ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '8', title: '8 Ut enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '9', title: '9 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '10', title: '10 Sed ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '11', title: '11 Ut enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '12', title: '12 Et harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '13', title: '13 Sed ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '14', title: '14 Uno enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '15', title: '15 Et harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '16', title: '16 Meni ut perspiciatis unde omnis iste et iusto odio?', body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    {id: '17', title: '17 Ut enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '18', title: '18 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '19', title: '19 Ut enim ad minima veniam', body: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.'},
    {id: '20', title: '20 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '21', title: '21 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '22', title: '22 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '23', title: '23 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
    {id: '24', title: '24 Ale harum quidem rerum facilis est et expedita distinctio!', body: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus, voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga'},
  ]
  constructor(private store: Store<PostsState>) {
    this.store.dispatch(new LoadPosts({posts: this.posts}));
  }
}
